#include<iostream>
using namespace std;
void divide(int x, int y, int z)
{
    cout<<"\n we are inside the function\n";
    if((x-y)!=0)
    {
        int R=z/(x-y);
        cout<<"Result="<<R<<"\n";
    }
    else
    {
        throw(x-y);
    }
}
int main()
{
    cout<<"swati"<<endl;
    try
    {
        cout<<"we are inside the try block\n";
        divide(10,20,30);
        divide(10,10,20);
    }
    catch(int i)
    {
        cout<<"caught the exception\n";
    }
    return 0;
}
